In [1]:
import numpy as np

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # THIS IS 1D ARRAY

newarr1 = arr.reshape(2, 3, 2) # WITH RESHAPE FUNCTION NOW CONVERTED IT INTO 3D ARRAY
newarr2 = arr.reshape(4,3) # WITH RESHAPE FUNCTION NOW CONVERTED IT INTO 2D ARRAY - not required now.

print(newarr1)


print(newarr2)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [4]:
newarr1 = [...,2]
print(newarr1)


[Ellipsis, 2]


In [5]:
newarr1 =[1,...]
print(newarr1)

[1, Ellipsis]


2.[]

In [6]:
import numpy as np
b = np.arange(0,20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
b1 = np.reshape(b,(5,4))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [8]:
b1[0,0]

np.int64(0)

In [9]:
b1[-1]

array([16, 17, 18, 19])

In [10]:
b1[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [11]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
b1>15


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [13]:
b1<=15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [14]:
a = np.array([ [ 0, 1, 2, 3, 4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34] ])
c = np.array( [True,False,True,False] ) # boolean row selector
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [15]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [16]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [17]:
d =  np.array([False,True,True,False,True])  # boolean column selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [18]:
 a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [19]:
i = np.array([0, 1, 2, 1]) # array of indices for the first axis
j = np.array([1,2,3,4]) # array of indices for the second axis

In [20]:
a[i,j]

array([ 1, 12, 23, 14])

3.Abs() and 4. Absolute -both are same -synonym for abs()

In [21]:
import numpy as np
ARR = np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [22]:
abs(ARR)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [23]:
ARR1 = 1.2 + 5j
ARR1


(1.2+5j)

In [24]:
abs(ARR1) #UNNDER-ROOT OF Square of of real part & imaginary part

5.141984052872976

In [25]:
np.absolute(ARR1) 

np.float64(5.141984052872976)

In [26]:
np.absolute([-10, -15])

array([10, 15])

5.ACCUMULATE
   -computes the sum of given initial value and elements in given range

In [27]:
import numpy as np

In [28]:
A1 = np.arange(0,10) 
print(A1) 

[0 1 2 3 4 5 6 7 8 9]


In [29]:
np.add.accumulate(A1) # Progressive SUM 

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [30]:
A2 = np.arange(1,6)

In [31]:
np.multiply.accumulate(A2)

array([  1,   2,   6,  24, 120])

In [32]:
AC = np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.add.accumulate(AC) # EVERY COLOMN GOT ACCUMULATE

array([[1, 2, 3],
       [5, 7, 9]])

In [34]:
np.multiply.accumulate(AC)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

6.Add

In [35]:
import numpy as np

In [36]:
ar1 = [2, -6]
ar2 = [1, 3]
ar3 = [2.2, 8.7]
ar4 = [7, -3]
print(ar1, ar2, ar3,  ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [37]:
np.add(ar1, ar2)

array([ 3, -3])

In [38]:
np.add(ar3, ar4)

array([9.2, 5.7])

In [39]:
C1 = 5+2j

In [40]:
np.add(ar3, C1)

array([ 7.2+2.j, 13.7+2.j])

7.All
---Test whether all array elements along a given axis evaluate to true

In [41]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.all(a>5)

np.False_

In [43]:
np.all(a>=0)

np.True_

In [44]:
b7 = np.array([True, False, True, True])
np.all(b7)

np.False_